swagger: '2.0'
info:
  description: >-
    This is the REST API for the Tool.
  version: 1.0.0
  title: Tool API

# Path API Definitions
paths:
  /bank:
    get:
      tags:
        - alm-kalkulation
      summary: 'List all banks available'
      parameters:
        - $ref: '#/parameters/searchKeyword'
      responses:
        200:
          description: 'Successful operation'
          schema:
            type: array
            items:
              $ref: '#/definitions/Bank'

# Data models
definitions:
  Bank:
    $ref: './models/bank.yml'

# Reusable Parameters
parameters:
  searchKeyword:
    name: searchKeyword
    in: query
    description: 'search keyword'
    required: false
    type: string
